version: '3'
services:
  postgres:
    image: 'postgres'
    container_name: 'java-postgres'
    ports:
      - "5434:5432"
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_DB=BankingTestDB'